{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "3d4903f7-f1b1-492b-a96f-ebb7f43b4cfc",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import nltk"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "cd93e849-60ac-475b-8492-61dc9bf6cb43",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Defaulting to user installation because normal site-packages is not writeable\n",
      "Collecting transformers\n",
      "  Using cached transformers-4.10.2-py3-none-any.whl (2.8 MB)\n",
      "Requirement already satisfied: numpy>=1.17 in /Users/andrew/Library/Python/3.8/lib/python/site-packages (from transformers) (1.20.3)\n",
      "Requirement already satisfied: regex!=2019.12.17 in /Users/andrew/Library/Python/3.8/lib/python/site-packages (from transformers) (2021.8.28)\n",
      "Collecting pyyaml>=5.1\n",
      "  Using cached PyYAML-5.4.1.tar.gz (175 kB)\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/normal'\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-it0y2157/overlay'\u001b[0m\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25ldone\n",
      "\u001b[?25h    Preparing wheel metadata ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting huggingface-hub>=0.0.12\n",
      "  Using cached huggingface_hub-0.0.17-py3-none-any.whl (52 kB)\n",
      "Collecting tokenizers<0.11,>=0.10.1\n",
      "  Using cached tokenizers-0.10.3.tar.gz (212 kB)\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/normal'\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-ery3h72n/overlay'\u001b[0m\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/tmp4g4ga0jd\n",
      "       cwd: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-install-4njqsg83/tokenizers_219a18d4ca9241728377bcc157f69765\n",
      "  Complete output (30 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 146, in get_requires_for_build_wheel\n",
      "      return self._get_build_requires(config_settings, requirements=['wheel'])\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 127, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 142, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 7, in <module>\n",
      "      setup(\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py\", line 145, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "      _setup_distribution = dist = klass(attrs)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py\", line 445, in __init__\n",
      "      _Distribution.__init__(self, {\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "      self.finalize_options()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py\", line 733, in finalize_options\n",
      "      ep.require(installer=self.fetch_build_egg)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2465, in require\n",
      "      items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 791, in resolve\n",
      "      raise VersionConflict(dist, req).with_context(dependent_req)\n",
      "  pkg_resources.VersionConflict: (setuptools 41.2.0 (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('setuptools>=46.1'))\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/48/2b/b99184cacb1a743edc18290e9127d1b0e658c0c46f2ab5290b27fe865ff4/tokenizers-0.10.3.tar.gz#sha256=1a5d3b596c6d3a237e1ad7f46c472d467b0246be7fd1a364f12576eb8db8f7e6 (from https://pypi.org/simple/tokenizers/). Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/tmp4g4ga0jd Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Using cached tokenizers-0.10.2.tar.gz (211 kB)\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/normal'\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-h9p79ni9/overlay'\u001b[0m\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "\u001b[31m  ERROR: Command errored out with exit status 1:\n",
      "   command: /Library/Developer/CommandLineTools/usr/bin/python3 /Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/tmpqkowesx5\n",
      "       cwd: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-install-4njqsg83/tokenizers_a3dc57d8665247cd88f056a5b1219138\n",
      "  Complete output (30 lines):\n",
      "  Traceback (most recent call last):\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 349, in <module>\n",
      "      main()\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 331, in main\n",
      "      json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "    File \"/Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py\", line 117, in get_requires_for_build_wheel\n",
      "      return hook(config_settings)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 146, in get_requires_for_build_wheel\n",
      "      return self._get_build_requires(config_settings, requirements=['wheel'])\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 127, in _get_build_requires\n",
      "      self.run_setup()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/build_meta.py\", line 142, in run_setup\n",
      "      exec(compile(code, __file__, 'exec'), locals())\n",
      "    File \"setup.py\", line 7, in <module>\n",
      "      setup(\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/__init__.py\", line 145, in setup\n",
      "      return distutils.core.setup(**attrs)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/core.py\", line 108, in setup\n",
      "      _setup_distribution = dist = klass(attrs)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py\", line 445, in __init__\n",
      "      _Distribution.__init__(self, {\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/distutils/dist.py\", line 292, in __init__\n",
      "      self.finalize_options()\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/setuptools/dist.py\", line 733, in finalize_options\n",
      "      ep.require(installer=self.fetch_build_egg)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 2465, in require\n",
      "      items = working_set.resolve(reqs, env, installer, extras=self.extras)\n",
      "    File \"/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages/pkg_resources/__init__.py\", line 791, in resolve\n",
      "      raise VersionConflict(dist, req).with_context(dependent_req)\n",
      "  pkg_resources.VersionConflict: (setuptools 41.2.0 (/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/site-packages), Requirement.parse('setuptools>=46.1'))\n",
      "  ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/05/96/d8f7a202cd46ac646b0aca2f3a7902bfefc70e9bd980e0371dba7fe7db85/tokenizers-0.10.2.tar.gz#sha256=cf7f1aad957fed36e4a90fc094e3adc03fdd45fbb058c1cde25721e3e66235f8 (from https://pypi.org/simple/tokenizers/). Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 /Users/andrew/Library/Python/3.8/lib/python/site-packages/pip/_vendor/pep517/in_process/_in_process.py get_requires_for_build_wheel /var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/tmpqkowesx5 Check the logs for full command output.\u001b[0m\n",
      "\u001b[?25h  Using cached tokenizers-0.10.1.tar.gz (210 kB)\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/normal/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/normal'\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>\n",
      "  distutils: /private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/overlay/lib/python3.8/site-packages\n",
      "  sysconfig: /Library/Python/3.8/site-packages\u001b[0m\n",
      "\u001b[33m  WARNING: Additional context:\n",
      "  user = False\n",
      "  home = None\n",
      "  root = None\n",
      "  prefix = '/private/var/folders/xf/9lz0m_yx41b0t1c62sn35swc0000gn/T/pip-build-env-vxfrgm_m/overlay'\u001b[0m\n",
      "  Installing build dependencies ... \u001b[?25l\\^C\n",
      "\u001b[?25canceled\n",
      "\u001b[31mERROR: Operation cancelled by user\u001b[0m\n"
     ]
    }
   ],
   "source": [
    "!pip3.8 install transformers\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "83bac73a-eb9e-4008-ba22-fada12677e90",
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'transformers'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-14-5abd615b8b0a>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mtransformers\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mAutoTokenizer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mAutoModelForSequenceClassification\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mtokenizer\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mAutoTokenizer\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_pretrained\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"sismetanin/xlm_roberta_large-ru-sentiment-rureviews\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mAutoModelForSequenceClassification\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfrom_pretrained\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"sismetanin/xlm_roberta_large-ru-sentiment-rureviews\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'transformers'"
     ]
    }
   ],
   "source": [
    "from transformers import AutoTokenizer, AutoModelForSequenceClassification\n",
    "  \n",
    "tokenizer = AutoTokenizer.from_pretrained(\"sismetanin/xlm_roberta_large-ru-sentiment-rureviews\")\n",
    "\n",
    "model = AutoModelForSequenceClassification.from_pretrained(\"sismetanin/xlm_roberta_large-ru-sentiment-rureviews\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e46a3b8b-ebc9-4717-b30f-453f82aac1ee",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "02ac2803-e783-446a-9e85-898c49559f40",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
